version: '3.8'

services:
  react:
    image: node:latest
    build:
      context: .
      dockerfile: DockerfileReact
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL:https://register-base-backend.vercel.app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  server-node_modules:
  react-node_modules:
