name: Build and Test React Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main&]

jobs:
  build_test:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify presence of package.json
        run: ls -la
      - name: Install dependencies and generate package-lock.json
        run: npm install
      - name: Clean install dependencies and run tests
        run: |
          npm ci
          npm test
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: Build the stack with Docker
        run: docker compose up -d
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: Run end-to-end tests with Cypress
        uses: cypress-io/github-action@v6
      - name: Stop the stack
        run: docker compose down
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate documentation and build project
        run: |
          npm run jsdoc
          npm run build --if-present
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
